---
- name: Verify that required string variables are defined
  assert:
    that: required_var is defined and required_var | length > 0 and required_var != None
    fail_msg: "{{ required_var }} needs to be set for the role to work "
    success_msg: "Required variable {{ required_var }} is defined"
  loop_control:
    loop_var: required_var
  with_items:
    - util__new_host
    - util__target_host
    - util__target_user
    
- name: Add new SSH host key to {{ util__target_host }}
  become_user: '{{ util__target_user }}'
  delegate_to: '{{ util__target_host }}'
  shell: ssh-keyscan -H {{ util__new_host }} >> ~/.ssh/known_hosts

- name: Remove any previous known_hosts for this IP address
  become_user: '{{ util__target_user }}'
  delegate_to: '{{ util__target_host }}'
  shell: ssh-keygen -R "$(getent hosts {{ util__new_host }} | awk '{ print $1 }')" 