kind: Secret
apiVersion: v1
metadata:
  name: sealed-secrets-keyq59z6
  generateName: sealed-secrets-key
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
data:
  {{ sealed_secrets__master_key_data | ternary(sealed_secrets__master_key_data, {}) | to_nice_yaml(indent=2) | indent(2) }}
type: kubernetes.io/tls
