all:
  children:

    servers:
      hosts:
        lockbox:
        pfsense:
        typhon:
          ansible_user: sean
    
    workstations:
      hosts:
        minerva:
          ansible_user: sean

  vars:
    ansible_user: pegasus
