---
- name: Start VMs
  delegate_to: toolbox
  community.general.proxmox_kvm:
    api_user: '{{ proxmox__api_user }}'
    api_password: '{{ proxmox__api_password }}'
    api_host: '{{ proxmox__api_host }}'
    name: '{{ inventory_hostname }}'
    node: '{{ vm__node }}'
    proxmox_default_behavior: no_defaults
    state: started
    timeout: '{{ vm__timeout }}'

- name: Wait for VM to be ready
  include_role:
    name: vm.wait-for