all:
  children:
    control_server:     # dynamically-created group of control-server nodes
    k3s_dev:            # dynamically-created group of k3s dev server nodes
    toolbox_group:            # dynamically-created group of toolbox server nodes

    proxmox_controller: # the host used to execute proxmox API calls from
      hosts:
        minerva:
   
    servers:
      children:
        control_server:
        k3s_dev:
      hosts:
        lockbox:
        pfsense:

    workstations:
      hosts:
        minerva:

