all:
  children:
    control_server:     # dynamically-created group of control-server nodes
    k3s_dev:            # dynamically-created group of k3s dev server nodes
    toolbox_group:      # dynamically-created group of toolbox server nodes
   
    servers:
      children:
        control_server:
        k3s_dev:
        toolbox_group:
      hosts:
        lockbox:
        pfsense:

    workstations:
      hosts:
        minerva:

