apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    {{ argocd__helm_repositories | ternary(argocd__helm_repositories, []) | to_nice_yaml(indent=2) | indent(4) }}
