---
- name: Verify that required string variables are defined
  assert:
    that: required_var is defined and required_var | length > 0 and required_var != None
    fail_msg: "{{ required_var }} needs to be set for the role to work "
    success_msg: "Required variable {{ required_var }} is defined"
  loop_control:
    loop_var: required_var
  with_items:
    - util__ssh_client_host
    - util__ssh_timeout

# we delay, because the SSH server is brought up by cloud-init before SSH keys are added...
- name: Wait for SSH keys to be authorized
  wait_for:
    timeout: '{{ util__ssh_timeout }}'
  delegate_to: '{{ util__ssh_client_host }}'

- name: Wait for cloud-init to finish
  wait_for:
    path: /var/run/cloud-init/status.json
    search_regex: '"stage": null'