#cloud-config
hostname: jump-host
chpasswd:
  expire: False
manage_etc_hosts: true
mounts:
  - [ swap ]
package_update: true
package_upgrade: true
packages:
  - git
  - qemu-guest-agent
runcmd:
  - git clone https://github.com/skleinjung/pegasus.git /home/pegasus/bootstrap
  - sh /home/pegasus/bootstrap/configurations/control/setup.sh
user: pegasus
users:
  - name: pegasus
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCggcZXYQcFadvoQbrz9FfAeYVfdgP1w/05duWpN9Cp3GNnhndKCPO0c6WyTiNN90eaTZTHnIVEXr0Jc6ebTKuv+yNTfOapw7v0gQfg24w7js4/Eruye0E/+ZSCltNv4UGqyzFin5HgApKLSItHRmXwZxvK12nWi2k6pd4VHnNW4kpFEgA6hibH1Sw2ZX4OZLXBUmLuhbjdxUuQYe4KUcizlOAWG520tF1sVB6FgOMN9O1u3++kd7cxum4/dIx+NGi5ZkEWWT5h5Nj2WdCTg6+sEt2T1MfB8W4CliAgAonK8mAZN7lBpllS0mUMOuSFFVQPpk9LufVpfVuAYbHRkP6p Sean@Archon
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
  - path: /etc/ansible/ansible.cfg
    content: |
      # See https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg
  - path: /etc/ssh/sshd_config
    content: |
      Include /etc/ssh/sshd_config.d/*.conf
      PermitRootLogin no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding yes
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem sftp	/usr/lib/openssh/sftp-server
      PasswordAuthentication no
      AllowUsers pegasus
  - path: /home/pegasus/certs/proxmox-ca-bundle.crt
    owner: "pegasus:pegasus"
    content: |
      -----BEGIN CERTIFICATE-----
      MIIFzTCCA7WgAwIBAgIUGaRMm0DfV/+4jVx9sFeNaNL5Vq8wDQYJKoZIhvcNAQEL
      BQAwdjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYD
      VQQLDCQ3MDZkNTk2My1lZDc0LTQ4YzItOGI3ZS0wNTBjNjZmNzFmNDcxHzAdBgNV
      BAoMFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwHhcNMjAxMjMwMDUxNzA0WhcNMzAx
      MjI4MDUxNzA0WjB2MSQwIgYDVQQDDBtQcm94bW94IFZpcnR1YWwgRW52aXJvbm1l
      bnQxLTArBgNVBAsMJDcwNmQ1OTYzLWVkNzQtNDhjMi04YjdlLTA1MGM2NmY3MWY0
      NzEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFuYWdlciBDQTCCAiIwDQYJKoZIhvcN
      AQEBBQADggIPADCCAgoCggIBAMWK0NP0bWWaoE2fRyrwIZqBwG19tUzaIHVUFiBy
      GnMGwkg4rY7aTgr5ReHTyy0LIidciL7Vcm2DGir5RkaZX+gwf2tygh130ASvMmtR
      koilkTlS8fNmgnzbVxNI+UenQXnUAJbNgZEKJGX3Nf96yzx2AO211veUtDOyMPhh
      O2EsZwREBPouCNzmpUzXjwywhAB1jkUzjJngRkyY/fbB3p3BqZbOy1rqkS15LECY
      ceQKhllYaYN7YUbdYzNbxR8sss0uqwEUfickuOXgAyLopqtJdkU1NIXRKEAeLcPu
      TNtYeQvxDBmeLK08f6gMc3V09fLLYJEKZzCnx2KOrDh4yo6wvkZtk6H+Za+ef/WP
      PFAiG1Ocz4xV3PpXUSpa6mPjlcwCICazi/9ZPd07prH78+kXWbGWBmfBspHVVhmq
      gcWQVBt4KKpV8xRiZyRgMgu+FQ7GtqhkrIfiyDQEVRY9i0eLgvF4nzpJaeg7ZBX/
      WmQ0Q5vx+dnWqx6U+6AYXUKqmodQJjkQZvAau6CJ3hjmlix440TtUWIWh8EdH5Hn
      xIl+Fv7Z5GyCi/pnt1t9BxVwPZq/BWAm0/S8e7jM4ipeQwfgNOWF+z7QNoh390l9
      gV64w93dxdyOZ1pC9Tg/lAkPlwLVoaD/QrW2K+c59cB81qpGj1UScVPqScFRYL9I
      /sJFAgMBAAGjUzBRMB0GA1UdDgQWBBTLd+jBnG2qZ0mOc9e0iMf0FF3QqjAfBgNV
      HSMEGDAWgBTLd+jBnG2qZ0mOc9e0iMf0FF3QqjAPBgNVHRMBAf8EBTADAQH/MA0G
      CSqGSIb3DQEBCwUAA4ICAQBLqzPLmIglty3yFkT7Fi/kFRmH+HgcokOzgsBda3JQ
      a/ewS/XLm1ZW8R2vRIaJtTYkV1tuSHKL9J6hMLOvmWZWILtWu+qjobwMeCH7HFXe
      vY/04o5/2K959D+VMnoHCpixtms9gtYsE7BgjE/Rqfyp/G+XdWEUkakR75nAgv6z
      djfJyZLOf+KoT9VFX3zEwwdMowE6smuXMM6GrBqXpTldwA16VB+X86gbDNYu938u
      CVhgCwgwEH90WFE/JGIgBgatve8bq1i1rRaJCdbFh9bMCggudcMSOf1KDXuI6Vs3
      K7rHc37ijpjtIM2fDQsLYk/00VQqHDY2YZeI3QFuDO3Fjt5PlBSuKE7lKd10ZJQm
      rIgn5YqrmPEky0xRG1wvlswEYLArY8BmoiT+3LTWqO+l387aRwr3Zns2o7Cq8D3d
      JhbTmEaH2bqut4zt7IGbEeqgKaf0+vSzi0VXzA6G7FxTmu/qMiY4lr3oRThgv5Ty
      lT5xO41pVqvbuvkZ9ssL/BiEikE5hv9nVkE88hslYJv+UoHGcemdfVz8zHTgFKAC
      ObSjPkLNU75m/IdvAhOJQ9Ooap+oPzDWOF5Go/yuRYKHH1a+eA7xzdU7TFnFEZNq
      woabaVBTKy3guAnQRywWk6MGDiWIlDAADZh+rijL3Wv5lN6xLfd9DP101W+mzs1T
      FQ==
      -----END CERTIFICATE-----
