---
- name: Create k3s-control-server VM
  hosts: proxmox_controller
  tasks:
  - name: Create new cloned VM
    include_role:
      name: proxmox.clone-vm
    vars:
      proxmox__balloon: 2048
      proxmox__clone_type: control-server
      proxmox__inventory_group: new_control_hosts
      proxmox__memory: 4096

  - name: Start new VM
    include_role:
      name: proxmox.start-vms
    vars:
      proxmox__new_vm_group: new_control_hosts
      proxmox__vm_names:
      - '{{ proxmox__clone_name }}'

- hosts: new_control_hosts
  gather_facts: no
  tasks:
    - name: Update ssh identity for {{ inventory_hostname }}
      include_role:
        name: util.update-ssh-identity
      vars:
        util__new_host: '{{ inventory_hostname }}'
        util__target_host: localhost
        util__target_user: sean

    - name: Wait for cloud-init to finish on {{ inventory_hostname }}
      include_role:
        name: util.wait-for-cloud-init
    
    - name: Perform initial patching
      include_role:
        name: apt-update