---
- name: Create k3s-control-server VM
  hosts: proxmox_controller
  # post_tasks:
  # - name: Reload inventory with new VM
  #   meta: refresh_inventory
  tasks:
  - name: Create new cloned VM
    include_role:
      name: proxmox.clone-vm
    vars:
      proxmox__balloon: 2048
      proxmox__clone_type: control-server
      proxmox__inventory_group: new_control_servers
      proxmox__memory: 4096
    when: not groups['control_servers']

- name: Initialize new control server
  hosts: "{{ groups['new_control_servers'] | default([]) }}"
  gather_facts: no
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: proxmox.start-vms
    
    - name: Update ssh identity for {{ inventory_hostname }}
      include_role:
        name: util.update-ssh-identity
      vars:
        util__new_host: '{{ inventory_hostname }}'
        util__target_host: localhost
        util__target_user: sean

    - name: Wait for cloud-init to finish on {{ inventory_hostname }}
      include_role:
        name: util.wait-for-cloud-init

- name: Ensure existing control server is running
  hosts: control_servers
  gather_facts: no
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: proxmox.start-vms

