---
- hosts: localhost
  tasks:
  - name: Create instance id
    set_fact:
      instance_id: "{{ lookup( 'password', '/dev/null length=32' ) | to_uuid | lower }}"
    delegate_to: localhost
    delegate_facts: true

  - name: Create random suffix for hostname
    set_fact:
      random_suffix: "{{ instance_id[:3] }}"
    delegate_to: localhost
    delegate_facts: true

- name: Set VM parameters as facts for all hosts
  hosts:
  - localhost
  - proxmox_controller
  - typhon
  tasks:
  - name: Set metadata facts
    set_fact:
      instance_id: "{{ hostvars['localhost'].instance_id }}"
      vm_name: control-server-{{ hostvars['localhost'].random_suffix }}
    
- name: Create updated cloud-init metadata
  hosts: typhon
  roles:
  - proxmox.install-cloud-init-configurations
  tasks:
  - name: Write cloud-init metadata
    copy:
      content: |
        instance-id: {{ instance_id }}
        instance_id: {{ instance_id }}
        local-hostname: {{ vm_name }}
        local_hostname: {{ vm_name }}
        vm_name: {{ vm_name }}
      dest: /large-pool/config/snippets/control-server-metadata.yml
      mode: u=rw,g=r,o=r
        
- name: Create k3s-control-server VM
  hosts: proxmox_controller
  tasks:
  - name: Clone VM template
    community.general.proxmox_kvm:
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      clone: ubuntu-server-20210104
      format: unspecified
      full: no
      name: '{{ vm_name }}'
      node: typhon
      proxmox_default_behavior: no_defaults
      state: present
      timeout: 30

  # API returns before the VMID can be looked up on the next step, so we delay just a bit
  - name: Wait for new VM to become consisent
    wait_for:
      timeout: 5
    delegate_to: localhost

  - name: Update VM configuration
    community.general.proxmox_kvm:
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      balloon: 2048
      cicustom: user=config:snippets/control-server-user-data.yml,meta=config:snippets/control-server-metadata.yml
      memory: 4096
      name: '{{ vm_name }}'
      node: typhon
      proxmox_default_behavior: no_defaults
      # TODO: need to create template with desired size...
      scsi:
        scsi0: 'size=+12G'
      state: present
      timeout: 30
      update: yes

  - name: Start new VM
    community.general.proxmox_kvm:
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      name: '{{ vm_name }}'
      node: typhon
      proxmox_default_behavior: no_defaults
      state: started
      timeout: 300

  - name: Add new VM to inventory
    add_host:
      name: '{{ vm_name }}'
      groups: new_vms

- hosts: new_vms
  gather_facts: no
  tasks:
    - name: Wait for SSH to be ready
      delegate_to: localhost
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10

    - name: Add new SSH host key to localhost
      become_user: sean
      delegate_to: localhost
      shell: ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts

    - name: Remove any previous known_hosts for this IP address
      become_user: sean
      delegate_to: localhost
      shell: ssh-keygen -R "$(getent hosts {{ inventory_hostname }} | awk '{ print $1 }')" 

    # we delay, because the SSH server is brought up by cloud-init before SSH keys are added...
    - name: Wait for SSH keys to be authorized
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Wait for cloud-init to finish
      wait_for:
        path: /var/run/cloud-init/status.json
        search_regex: '"stage": null'
    
    - name: Perform initial patching
      include_role:
        name: patch-os