---
- import_playbook: playbooks/proxmox.update-user-data.yml

- name: Create k3s-dev-server VM
  gather_facts: no
  hosts: toolbox
  post_tasks:
  - name: Update dynamic inventory
    meta: refresh_inventory
  tasks:
  - name: Create new cloned VM
    include_role:
      name: vm.clone
    vars:
      proxmox__balloon: 2048
      vm__clone_basename: k3s-dev-server
      vm__inventory_group: new_servers
      proxmox__memory: 4096
      vm__template: ubuntu-server-16gb-20210117
    when: not groups['k3s_dev']

- name: Ensure k3s-dev servers and agents are running
  gather_facts: no
  hosts: k3s_dev
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: vm.start

- name: Setup k3os cluster
  gather_facts: no
  hosts: k3s_dev
  tasks:
  - name: Apply k3s-server role
    include_role:
      name: k3s.server
    vars:
      k3s__nfs_enabled: true
      k3s__nfs_server: lockbox.pegasus
      k3s__nfs_path: /export/k3s-development

- name: Save cluster config locally
  become: true
  gather_facts: no
  hosts: k3s_dev[0]
  tasks:
  - name: Download cluster config
    include_role:
      name: k3s.fetch-config
    vars:
      k3s__config_path: /home/sean/.kube/config.d/{{ groups['k3s_dev'][0] }}