---
- name: Destroy k3s-dev-server VMs
  hosts: minerva
  tasks:
  - name: Stop k3s-dev-server VMs
    community.general.proxmox_kvm:
      api_user: '{{ proxmox__api_user }}'
      api_password: '{{ proxmox__api_password }}'
      api_host: '{{ proxmox__api_host }}'
      force: yes
      name: '{{ item }}'
      node: typhon
      proxmox_default_behavior: no_defaults
      state: stopped
      timeout: 300
    with_items:
    - "{{ groups['k3s_dev'] }}"

  # VM removal fails silently if it is not shut down, so we wait for VM to settle after stopping first
  - name: Wait for VMs to shutdown
    wait_for:
      timeout: 15

  - name: Remove k3s-dev VMs
    community.general.proxmox_kvm:
      api_user: '{{ proxmox__api_user }}'
      api_password: '{{ proxmox__api_password }}'
      api_host: '{{ proxmox__api_host }}'
      name: '{{ item }}'
      node: typhon
      proxmox_default_behavior: no_defaults
      state: absent
    with_items:
    - "{{ groups['k3s_dev'] }}"