---
- name: Create k3s-dev-server VM
  hosts: proxmox_controller
  tasks:
  - name: Create new cloned VM
    include_role:
      name: proxmox.clone-vm
    vars:
      proxmox__balloon: 2048
      proxmox__clone_type: k3s-dev-server
      proxmox__inventory_group: new_servers
      proxmox__memory: 4096
      proxmox__template: ubuntu-server-16gb-20210117
    when: not groups['k3s_dev']

- name: Ensure existing k3s-dev server is running
  hosts: k3s_dev
  gather_facts: no
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: proxmox.start-vms

- name: Ensure connectivity for new k3s-dev server
  hosts: "{{ groups['new_servers'] | default([]) }}"
  gather_facts: no
  post_tasks:
    - name: Add new VMs to inventory
      add_host:
        name: '{{ inventory_hostname }}'
        groups: k3s_dev
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: proxmox.start-vms
    
    - name: Update ssh identity for {{ inventory_hostname }}
      include_role:
        name: util.update-ssh-identity
      vars:
        util__new_host: '{{ inventory_hostname }}'
        util__target_host: localhost
        util__target_user: sean

    - name: Wait for cloud-init to finish on {{ inventory_hostname }}
      include_role:
        name: util.wait-for-cloud-init

- name: Setup k3os environment
  hosts: k3s_dev
  gather_facts: no
  tasks:
  - name: Apply k3s-server role
    include_role:
      name: k3s-server


