---
- import_playbook: playbooks/proxmox.update-user-data.yml

- name: Create k3s-dev-server VM
  hosts: toolbox
  post_tasks:
  - name: Update dynamic inventory
    meta: refresh_inventory
  tasks:
  - name: Create new cloned VM
    include_role:
      name: vm.clone
    vars:
      proxmox__balloon: 2048
      vm__clone_basename: k3s-dev-server
      vm__inventory_group: new_servers
      proxmox__memory: 4096
      vm__template: ubuntu-server-16gb-20210117
    when: not groups['k3s_dev']

- name: Ensure k3s-dev servers and agents are running
  hosts: k3s_dev
  gather_facts: no
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: vm.start

- name: Setup k3os environment
  hosts: k3s_dev
  gather_facts: no
  tasks:
  - name: Apply k3s-server role
    include_role:
      name: k3s-server
    vars:
      k3s_server__ip_end: 10.0.1.199
      k3s_server__ip_start: 10.0.1.100
      k3s_server__kubectl_users:
      - sean
      k3s_server__nfs_path: /export/k3s-development


