# mode: create | scale | update

---
- import_playbook: playbooks/proxmox.update-user-data.yml
- import_playbook: playbooks/k3s.provision-nodes.yml

- name: Ensure nodes are running for environment {{ environment_key }}
  gather_facts: no
  hosts: k3s_nodes,&{{ environment_key }}
  tasks:
    - name: Start VM - {{ inventory_hostname }}
      include_role:
        name: vm.start

- name: Configure k3s on servers for environment {{ environment_key }}
  gather_facts: no
  hosts: k3s_servers,&{{ environment_key }}
  tasks:
  - name: Load master key
    include_vars:
      file: config/k3s/{{ environment_key }}/master-key.yaml
      name: config
  - name: Apply k3s-server role
    include_role:
      name: k3s.server
    vars:
      k3s__nfs_enabled: true
      k3s__nfs_server: lockbox.pegasus
      k3s__nfs_path: /export/k3s-{{ environment_key }}
  - name: Set server host name as fact
    delegate_facts: yes
    delegate_to: toolbox
    ansible.builtin.set_fact:
      server_host: '{{ inventory_hostname }}'
  vars:
    argocd__admin_password_hash: "$2a$10$LeKBprcARUlaiqBpdFJHUux4KJD1/pmgeeG7QMXwg0hBElVmS1./S"
    argocd__root_application_path: root
    argocd__root_application_revision: '{{ environment_key }}'
    argocd__root_application_url: https://github.com/skleinjung/pegasus-deployments.git
    argocd__helm_repositories:
      - name: bitnami
        type: helm
        url: https://charts.bitnami.com/bitnami
      - name: traefik
        type: helm
        url: https://helm.traefik.io/traefik
    sealed_secrets__master_key: '{{ config.sealed_secrets_master_key }}'

- name: Configure k3s on agents for environment {{ environment_key }}
  gather_facts: no
  hosts: k3s_agents,&{{ environment_key }}
  tasks:
  - name: Apply k3s-agent role
    include_role:
      name: k3s.agent
    vars:
      k3s__server_host: "{{ hostvars['toolbox']['server_host'] }}"

- name: Save cluster server configs locally
  become: true
  gather_facts: no
  hosts: k3s_servers,&{{ environment_key }}
  tasks:
  - name: Download cluster config
    include_role:
      name: k3s.fetch-config
    vars:
      k3s__config_path: /home/sean/.kube/config.d/{{ inventory_hostname }}