# Master playbook for working with the toolbox vm.
# 
# Create VM: `ansible-playbook ... toolbox.yml -e new_vm_id=###`
#   Variables:
#     - max_memory: 4096
#     - min_memory: 2048
#     - proxmox_node: proxmox_nodes[0]
#     - template_id: 105
#
# Destroy VM: `ansible-playbook ... toolbox.yml -e destroy=true`
# Update VM: `ansible-playbook ... toolbox.yml`

---
- import_playbook: playbooks/toolbox.bootstrap.yml
- import_playbook: playbooks/toolbox.software.yml
